{
 "title": "CRUD users repository",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency (response time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "Quantile 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "Quantile 0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[1m])))",
     "legendFormat": "Quantile max"
    }
   ]
  },
  {
   "title": "Error rate (HTTP 400 and 500), RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "HTTP-400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "AVG-RPS"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m]))/sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "Duration (with actuator)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"/actuator/.*\"}[1m]))/sum(rate(http_server_requests_seconds_count{uri=~\"/actuator/.*\"}[1m]))",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}